// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

/**
 * <pre>
 * CAN data collection message
 * </pre>
 *
 * Protobuf type {@code edgetrip_v1.CanData}
 */
public final class CanData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:edgetrip_v1.CanData)
    CanDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CanData.newBuilder() to construct.
  private CanData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CanData() {
    gear_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CanData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_CanData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_CanData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tme.edgetrip.protos.CanData.class, tme.edgetrip.protos.CanData.Builder.class);
  }

  /**
   * <pre>
   * Active gear
   * </pre>
   *
   * Protobuf enum {@code edgetrip_v1.CanData.Gear}
   */
  public enum Gear
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>P_PARK = 1;</code>
     */
    P_PARK(1),
    /**
     * <code>D_DRIVE = 2;</code>
     */
    D_DRIVE(2),
    /**
     * <code>R_REVERSE = 3;</code>
     */
    R_REVERSE(3),
    /**
     * <code>N_NEUTRAL = 4;</code>
     */
    N_NEUTRAL(4),
    /**
     * <code>B_BRAKE = 5;</code>
     */
    B_BRAKE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>P_PARK = 1;</code>
     */
    public static final int P_PARK_VALUE = 1;
    /**
     * <code>D_DRIVE = 2;</code>
     */
    public static final int D_DRIVE_VALUE = 2;
    /**
     * <code>R_REVERSE = 3;</code>
     */
    public static final int R_REVERSE_VALUE = 3;
    /**
     * <code>N_NEUTRAL = 4;</code>
     */
    public static final int N_NEUTRAL_VALUE = 4;
    /**
     * <code>B_BRAKE = 5;</code>
     */
    public static final int B_BRAKE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gear valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gear forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return P_PARK;
        case 2: return D_DRIVE;
        case 3: return R_REVERSE;
        case 4: return N_NEUTRAL;
        case 5: return B_BRAKE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gear>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gear> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gear>() {
            public Gear findValueByNumber(int number) {
              return Gear.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return tme.edgetrip.protos.CanData.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gear[] VALUES = values();

    public static Gear valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gear(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:edgetrip_v1.CanData.Gear)
  }

  public static final int CANTIMESTAMP_FIELD_NUMBER = 1;
  private int canTimestamp_ = 0;
  /**
   * <pre>
   * UNIX timestamp of the data point
   * </pre>
   *
   * <code>int32 canTimestamp = 1;</code>
   * @return The canTimestamp.
   */
  @java.lang.Override
  public int getCanTimestamp() {
    return canTimestamp_;
  }

  public static final int SPEED_FIELD_NUMBER = 2;
  private double speed_ = 0D;
  /**
   * <pre>
   * Vehicle speed in kph
   * </pre>
   *
   * <code>double speed = 2;</code>
   * @return The speed.
   */
  @java.lang.Override
  public double getSpeed() {
    return speed_;
  }

  public static final int ACCFB_FIELD_NUMBER = 3;
  private double accFb_ = 0D;
  /**
   * <pre>
   * Front-Back acceleration in m/s2
   * </pre>
   *
   * <code>double accFb = 3;</code>
   * @return The accFb.
   */
  @java.lang.Override
  public double getAccFb() {
    return accFb_;
  }

  public static final int ACCRL_FIELD_NUMBER = 4;
  private double accRl_ = 0D;
  /**
   * <pre>
   * Right-Left acceleration in m/s2
   * </pre>
   *
   * <code>double accRl = 4;</code>
   * @return The accRl.
   */
  @java.lang.Override
  public double getAccRl() {
    return accRl_;
  }

  public static final int STATEOFCHARGE_FIELD_NUMBER = 5;
  private int stateOfCharge_ = 0;
  /**
   * <pre>
   * Battery state of charge 
   * </pre>
   *
   * <code>int32 stateOfCharge = 5;</code>
   * @return The stateOfCharge.
   */
  @java.lang.Override
  public int getStateOfCharge() {
    return stateOfCharge_;
  }

  public static final int GEAR_FIELD_NUMBER = 6;
  private int gear_ = 0;
  /**
   * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
   * @return The enum numeric value on the wire for gear.
   */
  @java.lang.Override public int getGearValue() {
    return gear_;
  }
  /**
   * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
   * @return The gear.
   */
  @java.lang.Override public tme.edgetrip.protos.CanData.Gear getGear() {
    tme.edgetrip.protos.CanData.Gear result = tme.edgetrip.protos.CanData.Gear.forNumber(gear_);
    return result == null ? tme.edgetrip.protos.CanData.Gear.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (canTimestamp_ != 0) {
      output.writeInt32(1, canTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(speed_) != 0) {
      output.writeDouble(2, speed_);
    }
    if (java.lang.Double.doubleToRawLongBits(accFb_) != 0) {
      output.writeDouble(3, accFb_);
    }
    if (java.lang.Double.doubleToRawLongBits(accRl_) != 0) {
      output.writeDouble(4, accRl_);
    }
    if (stateOfCharge_ != 0) {
      output.writeInt32(5, stateOfCharge_);
    }
    if (gear_ != tme.edgetrip.protos.CanData.Gear.UNKNOWN.getNumber()) {
      output.writeEnum(6, gear_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (canTimestamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, canTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(speed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, speed_);
    }
    if (java.lang.Double.doubleToRawLongBits(accFb_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, accFb_);
    }
    if (java.lang.Double.doubleToRawLongBits(accRl_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, accRl_);
    }
    if (stateOfCharge_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, stateOfCharge_);
    }
    if (gear_ != tme.edgetrip.protos.CanData.Gear.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, gear_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tme.edgetrip.protos.CanData)) {
      return super.equals(obj);
    }
    tme.edgetrip.protos.CanData other = (tme.edgetrip.protos.CanData) obj;

    if (getCanTimestamp()
        != other.getCanTimestamp()) return false;
    if (java.lang.Double.doubleToLongBits(getSpeed())
        != java.lang.Double.doubleToLongBits(
            other.getSpeed())) return false;
    if (java.lang.Double.doubleToLongBits(getAccFb())
        != java.lang.Double.doubleToLongBits(
            other.getAccFb())) return false;
    if (java.lang.Double.doubleToLongBits(getAccRl())
        != java.lang.Double.doubleToLongBits(
            other.getAccRl())) return false;
    if (getStateOfCharge()
        != other.getStateOfCharge()) return false;
    if (gear_ != other.gear_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getCanTimestamp();
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSpeed()));
    hash = (37 * hash) + ACCFB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAccFb()));
    hash = (37 * hash) + ACCRL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAccRl()));
    hash = (37 * hash) + STATEOFCHARGE_FIELD_NUMBER;
    hash = (53 * hash) + getStateOfCharge();
    hash = (37 * hash) + GEAR_FIELD_NUMBER;
    hash = (53 * hash) + gear_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tme.edgetrip.protos.CanData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) 
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.CanData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.CanData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tme.edgetrip.protos.CanData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tme.edgetrip.protos.CanData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.CanData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tme.edgetrip.protos.CanData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * CAN data collection message
   * </pre>
   *
   * Protobuf type {@code edgetrip_v1.CanData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:edgetrip_v1.CanData)
      tme.edgetrip.protos.CanDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_CanData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_CanData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tme.edgetrip.protos.CanData.class, tme.edgetrip.protos.CanData.Builder.class);
    }

    // Construct using tme.edgetrip.protos.CanData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      canTimestamp_ = 0;
      speed_ = 0D;
      accFb_ = 0D;
      accRl_ = 0D;
      stateOfCharge_ = 0;
      gear_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_CanData_descriptor;
    }

    @java.lang.Override
    public tme.edgetrip.protos.CanData getDefaultInstanceForType() {
      return tme.edgetrip.protos.CanData.getDefaultInstance();
    }

    @java.lang.Override
    public tme.edgetrip.protos.CanData build() {
      tme.edgetrip.protos.CanData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tme.edgetrip.protos.CanData buildPartial() {
      tme.edgetrip.protos.CanData result = new tme.edgetrip.protos.CanData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tme.edgetrip.protos.CanData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.canTimestamp_ = canTimestamp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.speed_ = speed_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.accFb_ = accFb_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.accRl_ = accRl_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.stateOfCharge_ = stateOfCharge_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.gear_ = gear_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tme.edgetrip.protos.CanData) {
        return mergeFrom((tme.edgetrip.protos.CanData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tme.edgetrip.protos.CanData other) {
      if (other == tme.edgetrip.protos.CanData.getDefaultInstance()) return this;
      if (other.getCanTimestamp() != 0) {
        setCanTimestamp(other.getCanTimestamp());
      }
      if (other.getSpeed() != 0D) {
        setSpeed(other.getSpeed());
      }
      if (other.getAccFb() != 0D) {
        setAccFb(other.getAccFb());
      }
      if (other.getAccRl() != 0D) {
        setAccRl(other.getAccRl());
      }
      if (other.getStateOfCharge() != 0) {
        setStateOfCharge(other.getStateOfCharge());
      }
      if (other.gear_ != 0) {
        setGearValue(other.getGearValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              canTimestamp_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              speed_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              accFb_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              accRl_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 40: {
              stateOfCharge_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              gear_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int canTimestamp_ ;
    /**
     * <pre>
     * UNIX timestamp of the data point
     * </pre>
     *
     * <code>int32 canTimestamp = 1;</code>
     * @return The canTimestamp.
     */
    @java.lang.Override
    public int getCanTimestamp() {
      return canTimestamp_;
    }
    /**
     * <pre>
     * UNIX timestamp of the data point
     * </pre>
     *
     * <code>int32 canTimestamp = 1;</code>
     * @param value The canTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setCanTimestamp(int value) {

      canTimestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UNIX timestamp of the data point
     * </pre>
     *
     * <code>int32 canTimestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      canTimestamp_ = 0;
      onChanged();
      return this;
    }

    private double speed_ ;
    /**
     * <pre>
     * Vehicle speed in kph
     * </pre>
     *
     * <code>double speed = 2;</code>
     * @return The speed.
     */
    @java.lang.Override
    public double getSpeed() {
      return speed_;
    }
    /**
     * <pre>
     * Vehicle speed in kph
     * </pre>
     *
     * <code>double speed = 2;</code>
     * @param value The speed to set.
     * @return This builder for chaining.
     */
    public Builder setSpeed(double value) {

      speed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vehicle speed in kph
     * </pre>
     *
     * <code>double speed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      speed_ = 0D;
      onChanged();
      return this;
    }

    private double accFb_ ;
    /**
     * <pre>
     * Front-Back acceleration in m/s2
     * </pre>
     *
     * <code>double accFb = 3;</code>
     * @return The accFb.
     */
    @java.lang.Override
    public double getAccFb() {
      return accFb_;
    }
    /**
     * <pre>
     * Front-Back acceleration in m/s2
     * </pre>
     *
     * <code>double accFb = 3;</code>
     * @param value The accFb to set.
     * @return This builder for chaining.
     */
    public Builder setAccFb(double value) {

      accFb_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Front-Back acceleration in m/s2
     * </pre>
     *
     * <code>double accFb = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccFb() {
      bitField0_ = (bitField0_ & ~0x00000004);
      accFb_ = 0D;
      onChanged();
      return this;
    }

    private double accRl_ ;
    /**
     * <pre>
     * Right-Left acceleration in m/s2
     * </pre>
     *
     * <code>double accRl = 4;</code>
     * @return The accRl.
     */
    @java.lang.Override
    public double getAccRl() {
      return accRl_;
    }
    /**
     * <pre>
     * Right-Left acceleration in m/s2
     * </pre>
     *
     * <code>double accRl = 4;</code>
     * @param value The accRl to set.
     * @return This builder for chaining.
     */
    public Builder setAccRl(double value) {

      accRl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Right-Left acceleration in m/s2
     * </pre>
     *
     * <code>double accRl = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccRl() {
      bitField0_ = (bitField0_ & ~0x00000008);
      accRl_ = 0D;
      onChanged();
      return this;
    }

    private int stateOfCharge_ ;
    /**
     * <pre>
     * Battery state of charge 
     * </pre>
     *
     * <code>int32 stateOfCharge = 5;</code>
     * @return The stateOfCharge.
     */
    @java.lang.Override
    public int getStateOfCharge() {
      return stateOfCharge_;
    }
    /**
     * <pre>
     * Battery state of charge 
     * </pre>
     *
     * <code>int32 stateOfCharge = 5;</code>
     * @param value The stateOfCharge to set.
     * @return This builder for chaining.
     */
    public Builder setStateOfCharge(int value) {

      stateOfCharge_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Battery state of charge 
     * </pre>
     *
     * <code>int32 stateOfCharge = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStateOfCharge() {
      bitField0_ = (bitField0_ & ~0x00000010);
      stateOfCharge_ = 0;
      onChanged();
      return this;
    }

    private int gear_ = 0;
    /**
     * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
     * @return The enum numeric value on the wire for gear.
     */
    @java.lang.Override public int getGearValue() {
      return gear_;
    }
    /**
     * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
     * @param value The enum numeric value on the wire for gear to set.
     * @return This builder for chaining.
     */
    public Builder setGearValue(int value) {
      gear_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
     * @return The gear.
     */
    @java.lang.Override
    public tme.edgetrip.protos.CanData.Gear getGear() {
      tme.edgetrip.protos.CanData.Gear result = tme.edgetrip.protos.CanData.Gear.forNumber(gear_);
      return result == null ? tme.edgetrip.protos.CanData.Gear.UNRECOGNIZED : result;
    }
    /**
     * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
     * @param value The gear to set.
     * @return This builder for chaining.
     */
    public Builder setGear(tme.edgetrip.protos.CanData.Gear value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      gear_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.edgetrip_v1.CanData.Gear gear = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGear() {
      bitField0_ = (bitField0_ & ~0x00000020);
      gear_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:edgetrip_v1.CanData)
  }

  // @@protoc_insertion_point(class_scope:edgetrip_v1.CanData)
  private static final tme.edgetrip.protos.CanData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tme.edgetrip.protos.CanData();
  }

  public static tme.edgetrip.protos.CanData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CanData>
      PARSER = new com.google.protobuf.AbstractParser<CanData>() {
    @java.lang.Override
    public CanData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CanData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CanData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tme.edgetrip.protos.CanData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

