// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

public interface DrivingScoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:edgetrip_v1.DrivingScore)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ECO Start score value
   * </pre>
   *
   * <code>double ecoStartScore = 1;</code>
   * @return The ecoStartScore.
   */
  double getEcoStartScore();

  /**
   * <pre>
   * ECO Steady score value
   * </pre>
   *
   * <code>double ecoSteadyScore = 2;</code>
   * @return The ecoSteadyScore.
   */
  double getEcoSteadyScore();

  /**
   * <pre>
   * ECO Decel score value
   * </pre>
   *
   * <code>double ecoDecelScore = 3;</code>
   * @return The ecoDecelScore.
   */
  double getEcoDecelScore();
}
