// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

public final class EdgeTripProtos {
  private EdgeTripProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edgetrip_v1_PositionInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edgetrip_v1_PositionInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edgetrip_v1_TripSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edgetrip_v1_TripSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edgetrip_v1_LocationData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edgetrip_v1_LocationData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edgetrip_v1_CanData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edgetrip_v1_CanData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edgetrip_v1_DrivingScore_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edgetrip_v1_DrivingScore_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edgetrip_v1_EdgeTripMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edgetrip_v1_EdgeTripMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021edgetrip_v1.proto\022\013edgetrip_v1\":\n\023Posi" +
      "tionInformation\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlon" +
      "gitude\030\002 \001(\001\"\350\002\n\013TripSummary\022\025\n\rtripStar" +
      "tTime\030\001 \001(\005\022;\n\021tripStartLocation\030\002 \001(\0132 " +
      ".edgetrip_v1.PositionInformation\022\023\n\013trip" +
      "EndTime\030\003 \001(\005\0229\n\017tripEndLocation\030\004 \001(\0132 " +
      ".edgetrip_v1.PositionInformation\022\022\n\ntrip" +
      "Length\030\005 \001(\001\022\024\n\014tripDuration\030\006 \001(\005\022\030\n\020tr" +
      "ipDurationIdle\030\007 \001(\005\022\033\n\023tripDurationHigh" +
      "way\030\010 \001(\005\022\024\n\014tripMaxSpeed\030\t \001(\001\022\024\n\014tripA" +
      "vgSpeed\030\n \001(\001\022\024\n\014socStartTrip\030\013 \001(\005\022\022\n\ns" +
      "ocEndTrip\030\014 \001(\005\"]\n\014LocationData\022\031\n\021locat" +
      "ionTimestamp\030\001 \001(\005\0222\n\010position\030\002 \001(\0132 .e" +
      "dgetrip_v1.PositionInformation\"\345\001\n\007CanDa" +
      "ta\022\024\n\014canTimestamp\030\001 \001(\005\022\r\n\005speed\030\002 \001(\001\022" +
      "\r\n\005accFb\030\003 \001(\001\022\r\n\005accRl\030\004 \001(\001\022\025\n\rstateOf" +
      "Charge\030\005 \001(\005\022\'\n\004gear\030\006 \001(\0162\031.edgetrip_v1" +
      ".CanData.Gear\"W\n\004Gear\022\013\n\007UNKNOWN\020\000\022\n\n\006P_" +
      "PARK\020\001\022\013\n\007D_DRIVE\020\002\022\r\n\tR_REVERSE\020\003\022\r\n\tN_" +
      "NEUTRAL\020\004\022\013\n\007B_BRAKE\020\005\"T\n\014DrivingScore\022\025" +
      "\n\recoStartScore\030\001 \001(\001\022\026\n\016ecoSteadyScore\030" +
      "\002 \001(\001\022\025\n\recoDecelScore\030\003 \001(\001\"\367\001\n\017EdgeTri" +
      "pMessage\022\027\n\017messageCreation\030\001 \001(\005\022\023\n\013dat" +
      "aVersion\030\002 \001(\005\022-\n\013tripSummary\030\003 \001(\0132\030.ed" +
      "getrip_v1.TripSummary\022/\n\014locationData\030\004 " +
      "\003(\0132\031.edgetrip_v1.LocationData\022%\n\007canDat" +
      "a\030\005 \003(\0132\024.edgetrip_v1.CanData\022/\n\014driving" +
      "Score\030\006 \001(\0132\031.edgetrip_v1.DrivingScoreB\'" +
      "\n\023tme.edgetrip.protosB\016EdgeTripProtosP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_edgetrip_v1_PositionInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edgetrip_v1_PositionInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edgetrip_v1_PositionInformation_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_edgetrip_v1_TripSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edgetrip_v1_TripSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edgetrip_v1_TripSummary_descriptor,
        new java.lang.String[] { "TripStartTime", "TripStartLocation", "TripEndTime", "TripEndLocation", "TripLength", "TripDuration", "TripDurationIdle", "TripDurationHighway", "TripMaxSpeed", "TripAvgSpeed", "SocStartTrip", "SocEndTrip", });
    internal_static_edgetrip_v1_LocationData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_edgetrip_v1_LocationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edgetrip_v1_LocationData_descriptor,
        new java.lang.String[] { "LocationTimestamp", "Position", });
    internal_static_edgetrip_v1_CanData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_edgetrip_v1_CanData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edgetrip_v1_CanData_descriptor,
        new java.lang.String[] { "CanTimestamp", "Speed", "AccFb", "AccRl", "StateOfCharge", "Gear", });
    internal_static_edgetrip_v1_DrivingScore_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_edgetrip_v1_DrivingScore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edgetrip_v1_DrivingScore_descriptor,
        new java.lang.String[] { "EcoStartScore", "EcoSteadyScore", "EcoDecelScore", });
    internal_static_edgetrip_v1_EdgeTripMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_edgetrip_v1_EdgeTripMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edgetrip_v1_EdgeTripMessage_descriptor,
        new java.lang.String[] { "MessageCreation", "DataVersion", "TripSummary", "LocationData", "CanData", "DrivingScore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
