// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

/**
 * <pre>
 * Main Edge Trip message
 * </pre>
 *
 * Protobuf type {@code edgetrip_v1.EdgeTripMessage}
 */
public final class EdgeTripMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:edgetrip_v1.EdgeTripMessage)
    EdgeTripMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EdgeTripMessage.newBuilder() to construct.
  private EdgeTripMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EdgeTripMessage() {
    locationData_ = java.util.Collections.emptyList();
    canData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EdgeTripMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_EdgeTripMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_EdgeTripMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tme.edgetrip.protos.EdgeTripMessage.class, tme.edgetrip.protos.EdgeTripMessage.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGECREATION_FIELD_NUMBER = 1;
  private int messageCreation_ = 0;
  /**
   * <pre>
   * UNIX timestamp of the creation of the trip message (YYYY_MM_DD HH:MM:SS)
   * </pre>
   *
   * <code>int32 messageCreation = 1;</code>
   * @return The messageCreation.
   */
  @java.lang.Override
  public int getMessageCreation() {
    return messageCreation_;
  }

  public static final int DATAVERSION_FIELD_NUMBER = 2;
  private int dataVersion_ = 0;
  /**
   * <pre>
   * Version of the protobuf data schema (1)
   * </pre>
   *
   * <code>int32 dataVersion = 2;</code>
   * @return The dataVersion.
   */
  @java.lang.Override
  public int getDataVersion() {
    return dataVersion_;
  }

  public static final int TRIPSUMMARY_FIELD_NUMBER = 3;
  private tme.edgetrip.protos.TripSummary tripSummary_;
  /**
   * <pre>
   * Trip Summary Data
   * </pre>
   *
   * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
   * @return Whether the tripSummary field is set.
   */
  @java.lang.Override
  public boolean hasTripSummary() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Trip Summary Data
   * </pre>
   *
   * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
   * @return The tripSummary.
   */
  @java.lang.Override
  public tme.edgetrip.protos.TripSummary getTripSummary() {
    return tripSummary_ == null ? tme.edgetrip.protos.TripSummary.getDefaultInstance() : tripSummary_;
  }
  /**
   * <pre>
   * Trip Summary Data
   * </pre>
   *
   * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.TripSummaryOrBuilder getTripSummaryOrBuilder() {
    return tripSummary_ == null ? tme.edgetrip.protos.TripSummary.getDefaultInstance() : tripSummary_;
  }

  public static final int LOCATIONDATA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<tme.edgetrip.protos.LocationData> locationData_;
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  @java.lang.Override
  public java.util.List<tme.edgetrip.protos.LocationData> getLocationDataList() {
    return locationData_;
  }
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends tme.edgetrip.protos.LocationDataOrBuilder> 
      getLocationDataOrBuilderList() {
    return locationData_;
  }
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  @java.lang.Override
  public int getLocationDataCount() {
    return locationData_.size();
  }
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.LocationData getLocationData(int index) {
    return locationData_.get(index);
  }
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.LocationDataOrBuilder getLocationDataOrBuilder(
      int index) {
    return locationData_.get(index);
  }

  public static final int CANDATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<tme.edgetrip.protos.CanData> canData_;
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  @java.lang.Override
  public java.util.List<tme.edgetrip.protos.CanData> getCanDataList() {
    return canData_;
  }
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends tme.edgetrip.protos.CanDataOrBuilder> 
      getCanDataOrBuilderList() {
    return canData_;
  }
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  @java.lang.Override
  public int getCanDataCount() {
    return canData_.size();
  }
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.CanData getCanData(int index) {
    return canData_.get(index);
  }
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.CanDataOrBuilder getCanDataOrBuilder(
      int index) {
    return canData_.get(index);
  }

  public static final int DRIVINGSCORE_FIELD_NUMBER = 6;
  private tme.edgetrip.protos.DrivingScore drivingScore_;
  /**
   * <pre>
   * Hybrid Score
   * </pre>
   *
   * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
   * @return Whether the drivingScore field is set.
   */
  @java.lang.Override
  public boolean hasDrivingScore() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Hybrid Score
   * </pre>
   *
   * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
   * @return The drivingScore.
   */
  @java.lang.Override
  public tme.edgetrip.protos.DrivingScore getDrivingScore() {
    return drivingScore_ == null ? tme.edgetrip.protos.DrivingScore.getDefaultInstance() : drivingScore_;
  }
  /**
   * <pre>
   * Hybrid Score
   * </pre>
   *
   * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.DrivingScoreOrBuilder getDrivingScoreOrBuilder() {
    return drivingScore_ == null ? tme.edgetrip.protos.DrivingScore.getDefaultInstance() : drivingScore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCreation_ != 0) {
      output.writeInt32(1, messageCreation_);
    }
    if (dataVersion_ != 0) {
      output.writeInt32(2, dataVersion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getTripSummary());
    }
    for (int i = 0; i < locationData_.size(); i++) {
      output.writeMessage(4, locationData_.get(i));
    }
    for (int i = 0; i < canData_.size(); i++) {
      output.writeMessage(5, canData_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getDrivingScore());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageCreation_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, messageCreation_);
    }
    if (dataVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, dataVersion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTripSummary());
    }
    for (int i = 0; i < locationData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, locationData_.get(i));
    }
    for (int i = 0; i < canData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, canData_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDrivingScore());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tme.edgetrip.protos.EdgeTripMessage)) {
      return super.equals(obj);
    }
    tme.edgetrip.protos.EdgeTripMessage other = (tme.edgetrip.protos.EdgeTripMessage) obj;

    if (getMessageCreation()
        != other.getMessageCreation()) return false;
    if (getDataVersion()
        != other.getDataVersion()) return false;
    if (hasTripSummary() != other.hasTripSummary()) return false;
    if (hasTripSummary()) {
      if (!getTripSummary()
          .equals(other.getTripSummary())) return false;
    }
    if (!getLocationDataList()
        .equals(other.getLocationDataList())) return false;
    if (!getCanDataList()
        .equals(other.getCanDataList())) return false;
    if (hasDrivingScore() != other.hasDrivingScore()) return false;
    if (hasDrivingScore()) {
      if (!getDrivingScore()
          .equals(other.getDrivingScore())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGECREATION_FIELD_NUMBER;
    hash = (53 * hash) + getMessageCreation();
    hash = (37 * hash) + DATAVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getDataVersion();
    if (hasTripSummary()) {
      hash = (37 * hash) + TRIPSUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getTripSummary().hashCode();
    }
    if (getLocationDataCount() > 0) {
      hash = (37 * hash) + LOCATIONDATA_FIELD_NUMBER;
      hash = (53 * hash) + getLocationDataList().hashCode();
    }
    if (getCanDataCount() > 0) {
      hash = (37 * hash) + CANDATA_FIELD_NUMBER;
      hash = (53 * hash) + getCanDataList().hashCode();
    }
    if (hasDrivingScore()) {
      hash = (37 * hash) + DRIVINGSCORE_FIELD_NUMBER;
      hash = (53 * hash) + getDrivingScore().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tme.edgetrip.protos.EdgeTripMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tme.edgetrip.protos.EdgeTripMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.EdgeTripMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tme.edgetrip.protos.EdgeTripMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Main Edge Trip message
   * </pre>
   *
   * Protobuf type {@code edgetrip_v1.EdgeTripMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:edgetrip_v1.EdgeTripMessage)
      tme.edgetrip.protos.EdgeTripMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_EdgeTripMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_EdgeTripMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tme.edgetrip.protos.EdgeTripMessage.class, tme.edgetrip.protos.EdgeTripMessage.Builder.class);
    }

    // Construct using tme.edgetrip.protos.EdgeTripMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTripSummaryFieldBuilder();
        getLocationDataFieldBuilder();
        getCanDataFieldBuilder();
        getDrivingScoreFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageCreation_ = 0;
      dataVersion_ = 0;
      tripSummary_ = null;
      if (tripSummaryBuilder_ != null) {
        tripSummaryBuilder_.dispose();
        tripSummaryBuilder_ = null;
      }
      if (locationDataBuilder_ == null) {
        locationData_ = java.util.Collections.emptyList();
      } else {
        locationData_ = null;
        locationDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (canDataBuilder_ == null) {
        canData_ = java.util.Collections.emptyList();
      } else {
        canData_ = null;
        canDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      drivingScore_ = null;
      if (drivingScoreBuilder_ != null) {
        drivingScoreBuilder_.dispose();
        drivingScoreBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_EdgeTripMessage_descriptor;
    }

    @java.lang.Override
    public tme.edgetrip.protos.EdgeTripMessage getDefaultInstanceForType() {
      return tme.edgetrip.protos.EdgeTripMessage.getDefaultInstance();
    }

    @java.lang.Override
    public tme.edgetrip.protos.EdgeTripMessage build() {
      tme.edgetrip.protos.EdgeTripMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tme.edgetrip.protos.EdgeTripMessage buildPartial() {
      tme.edgetrip.protos.EdgeTripMessage result = new tme.edgetrip.protos.EdgeTripMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(tme.edgetrip.protos.EdgeTripMessage result) {
      if (locationDataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          locationData_ = java.util.Collections.unmodifiableList(locationData_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.locationData_ = locationData_;
      } else {
        result.locationData_ = locationDataBuilder_.build();
      }
      if (canDataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          canData_ = java.util.Collections.unmodifiableList(canData_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.canData_ = canData_;
      } else {
        result.canData_ = canDataBuilder_.build();
      }
    }

    private void buildPartial0(tme.edgetrip.protos.EdgeTripMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageCreation_ = messageCreation_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dataVersion_ = dataVersion_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tripSummary_ = tripSummaryBuilder_ == null
            ? tripSummary_
            : tripSummaryBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.drivingScore_ = drivingScoreBuilder_ == null
            ? drivingScore_
            : drivingScoreBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tme.edgetrip.protos.EdgeTripMessage) {
        return mergeFrom((tme.edgetrip.protos.EdgeTripMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tme.edgetrip.protos.EdgeTripMessage other) {
      if (other == tme.edgetrip.protos.EdgeTripMessage.getDefaultInstance()) return this;
      if (other.getMessageCreation() != 0) {
        setMessageCreation(other.getMessageCreation());
      }
      if (other.getDataVersion() != 0) {
        setDataVersion(other.getDataVersion());
      }
      if (other.hasTripSummary()) {
        mergeTripSummary(other.getTripSummary());
      }
      if (locationDataBuilder_ == null) {
        if (!other.locationData_.isEmpty()) {
          if (locationData_.isEmpty()) {
            locationData_ = other.locationData_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLocationDataIsMutable();
            locationData_.addAll(other.locationData_);
          }
          onChanged();
        }
      } else {
        if (!other.locationData_.isEmpty()) {
          if (locationDataBuilder_.isEmpty()) {
            locationDataBuilder_.dispose();
            locationDataBuilder_ = null;
            locationData_ = other.locationData_;
            bitField0_ = (bitField0_ & ~0x00000008);
            locationDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLocationDataFieldBuilder() : null;
          } else {
            locationDataBuilder_.addAllMessages(other.locationData_);
          }
        }
      }
      if (canDataBuilder_ == null) {
        if (!other.canData_.isEmpty()) {
          if (canData_.isEmpty()) {
            canData_ = other.canData_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCanDataIsMutable();
            canData_.addAll(other.canData_);
          }
          onChanged();
        }
      } else {
        if (!other.canData_.isEmpty()) {
          if (canDataBuilder_.isEmpty()) {
            canDataBuilder_.dispose();
            canDataBuilder_ = null;
            canData_ = other.canData_;
            bitField0_ = (bitField0_ & ~0x00000010);
            canDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCanDataFieldBuilder() : null;
          } else {
            canDataBuilder_.addAllMessages(other.canData_);
          }
        }
      }
      if (other.hasDrivingScore()) {
        mergeDrivingScore(other.getDrivingScore());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageCreation_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              dataVersion_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getTripSummaryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              tme.edgetrip.protos.LocationData m =
                  input.readMessage(
                      tme.edgetrip.protos.LocationData.parser(),
                      extensionRegistry);
              if (locationDataBuilder_ == null) {
                ensureLocationDataIsMutable();
                locationData_.add(m);
              } else {
                locationDataBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              tme.edgetrip.protos.CanData m =
                  input.readMessage(
                      tme.edgetrip.protos.CanData.parser(),
                      extensionRegistry);
              if (canDataBuilder_ == null) {
                ensureCanDataIsMutable();
                canData_.add(m);
              } else {
                canDataBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getDrivingScoreFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int messageCreation_ ;
    /**
     * <pre>
     * UNIX timestamp of the creation of the trip message (YYYY_MM_DD HH:MM:SS)
     * </pre>
     *
     * <code>int32 messageCreation = 1;</code>
     * @return The messageCreation.
     */
    @java.lang.Override
    public int getMessageCreation() {
      return messageCreation_;
    }
    /**
     * <pre>
     * UNIX timestamp of the creation of the trip message (YYYY_MM_DD HH:MM:SS)
     * </pre>
     *
     * <code>int32 messageCreation = 1;</code>
     * @param value The messageCreation to set.
     * @return This builder for chaining.
     */
    public Builder setMessageCreation(int value) {

      messageCreation_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UNIX timestamp of the creation of the trip message (YYYY_MM_DD HH:MM:SS)
     * </pre>
     *
     * <code>int32 messageCreation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageCreation() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageCreation_ = 0;
      onChanged();
      return this;
    }

    private int dataVersion_ ;
    /**
     * <pre>
     * Version of the protobuf data schema (1)
     * </pre>
     *
     * <code>int32 dataVersion = 2;</code>
     * @return The dataVersion.
     */
    @java.lang.Override
    public int getDataVersion() {
      return dataVersion_;
    }
    /**
     * <pre>
     * Version of the protobuf data schema (1)
     * </pre>
     *
     * <code>int32 dataVersion = 2;</code>
     * @param value The dataVersion to set.
     * @return This builder for chaining.
     */
    public Builder setDataVersion(int value) {

      dataVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the protobuf data schema (1)
     * </pre>
     *
     * <code>int32 dataVersion = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dataVersion_ = 0;
      onChanged();
      return this;
    }

    private tme.edgetrip.protos.TripSummary tripSummary_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.TripSummary, tme.edgetrip.protos.TripSummary.Builder, tme.edgetrip.protos.TripSummaryOrBuilder> tripSummaryBuilder_;
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     * @return Whether the tripSummary field is set.
     */
    public boolean hasTripSummary() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     * @return The tripSummary.
     */
    public tme.edgetrip.protos.TripSummary getTripSummary() {
      if (tripSummaryBuilder_ == null) {
        return tripSummary_ == null ? tme.edgetrip.protos.TripSummary.getDefaultInstance() : tripSummary_;
      } else {
        return tripSummaryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    public Builder setTripSummary(tme.edgetrip.protos.TripSummary value) {
      if (tripSummaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tripSummary_ = value;
      } else {
        tripSummaryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    public Builder setTripSummary(
        tme.edgetrip.protos.TripSummary.Builder builderForValue) {
      if (tripSummaryBuilder_ == null) {
        tripSummary_ = builderForValue.build();
      } else {
        tripSummaryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    public Builder mergeTripSummary(tme.edgetrip.protos.TripSummary value) {
      if (tripSummaryBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          tripSummary_ != null &&
          tripSummary_ != tme.edgetrip.protos.TripSummary.getDefaultInstance()) {
          getTripSummaryBuilder().mergeFrom(value);
        } else {
          tripSummary_ = value;
        }
      } else {
        tripSummaryBuilder_.mergeFrom(value);
      }
      if (tripSummary_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    public Builder clearTripSummary() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tripSummary_ = null;
      if (tripSummaryBuilder_ != null) {
        tripSummaryBuilder_.dispose();
        tripSummaryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    public tme.edgetrip.protos.TripSummary.Builder getTripSummaryBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTripSummaryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    public tme.edgetrip.protos.TripSummaryOrBuilder getTripSummaryOrBuilder() {
      if (tripSummaryBuilder_ != null) {
        return tripSummaryBuilder_.getMessageOrBuilder();
      } else {
        return tripSummary_ == null ?
            tme.edgetrip.protos.TripSummary.getDefaultInstance() : tripSummary_;
      }
    }
    /**
     * <pre>
     * Trip Summary Data
     * </pre>
     *
     * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.TripSummary, tme.edgetrip.protos.TripSummary.Builder, tme.edgetrip.protos.TripSummaryOrBuilder> 
        getTripSummaryFieldBuilder() {
      if (tripSummaryBuilder_ == null) {
        tripSummaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tme.edgetrip.protos.TripSummary, tme.edgetrip.protos.TripSummary.Builder, tme.edgetrip.protos.TripSummaryOrBuilder>(
                getTripSummary(),
                getParentForChildren(),
                isClean());
        tripSummary_ = null;
      }
      return tripSummaryBuilder_;
    }

    private java.util.List<tme.edgetrip.protos.LocationData> locationData_ =
      java.util.Collections.emptyList();
    private void ensureLocationDataIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        locationData_ = new java.util.ArrayList<tme.edgetrip.protos.LocationData>(locationData_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        tme.edgetrip.protos.LocationData, tme.edgetrip.protos.LocationData.Builder, tme.edgetrip.protos.LocationDataOrBuilder> locationDataBuilder_;

    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public java.util.List<tme.edgetrip.protos.LocationData> getLocationDataList() {
      if (locationDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(locationData_);
      } else {
        return locationDataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public int getLocationDataCount() {
      if (locationDataBuilder_ == null) {
        return locationData_.size();
      } else {
        return locationDataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public tme.edgetrip.protos.LocationData getLocationData(int index) {
      if (locationDataBuilder_ == null) {
        return locationData_.get(index);
      } else {
        return locationDataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder setLocationData(
        int index, tme.edgetrip.protos.LocationData value) {
      if (locationDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationDataIsMutable();
        locationData_.set(index, value);
        onChanged();
      } else {
        locationDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder setLocationData(
        int index, tme.edgetrip.protos.LocationData.Builder builderForValue) {
      if (locationDataBuilder_ == null) {
        ensureLocationDataIsMutable();
        locationData_.set(index, builderForValue.build());
        onChanged();
      } else {
        locationDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder addLocationData(tme.edgetrip.protos.LocationData value) {
      if (locationDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationDataIsMutable();
        locationData_.add(value);
        onChanged();
      } else {
        locationDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder addLocationData(
        int index, tme.edgetrip.protos.LocationData value) {
      if (locationDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationDataIsMutable();
        locationData_.add(index, value);
        onChanged();
      } else {
        locationDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder addLocationData(
        tme.edgetrip.protos.LocationData.Builder builderForValue) {
      if (locationDataBuilder_ == null) {
        ensureLocationDataIsMutable();
        locationData_.add(builderForValue.build());
        onChanged();
      } else {
        locationDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder addLocationData(
        int index, tme.edgetrip.protos.LocationData.Builder builderForValue) {
      if (locationDataBuilder_ == null) {
        ensureLocationDataIsMutable();
        locationData_.add(index, builderForValue.build());
        onChanged();
      } else {
        locationDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder addAllLocationData(
        java.lang.Iterable<? extends tme.edgetrip.protos.LocationData> values) {
      if (locationDataBuilder_ == null) {
        ensureLocationDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, locationData_);
        onChanged();
      } else {
        locationDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder clearLocationData() {
      if (locationDataBuilder_ == null) {
        locationData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        locationDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public Builder removeLocationData(int index) {
      if (locationDataBuilder_ == null) {
        ensureLocationDataIsMutable();
        locationData_.remove(index);
        onChanged();
      } else {
        locationDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public tme.edgetrip.protos.LocationData.Builder getLocationDataBuilder(
        int index) {
      return getLocationDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public tme.edgetrip.protos.LocationDataOrBuilder getLocationDataOrBuilder(
        int index) {
      if (locationDataBuilder_ == null) {
        return locationData_.get(index);  } else {
        return locationDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public java.util.List<? extends tme.edgetrip.protos.LocationDataOrBuilder> 
         getLocationDataOrBuilderList() {
      if (locationDataBuilder_ != null) {
        return locationDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(locationData_);
      }
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public tme.edgetrip.protos.LocationData.Builder addLocationDataBuilder() {
      return getLocationDataFieldBuilder().addBuilder(
          tme.edgetrip.protos.LocationData.getDefaultInstance());
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public tme.edgetrip.protos.LocationData.Builder addLocationDataBuilder(
        int index) {
      return getLocationDataFieldBuilder().addBuilder(
          index, tme.edgetrip.protos.LocationData.getDefaultInstance());
    }
    /**
     * <pre>
     * Periodic Location Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
     */
    public java.util.List<tme.edgetrip.protos.LocationData.Builder> 
         getLocationDataBuilderList() {
      return getLocationDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        tme.edgetrip.protos.LocationData, tme.edgetrip.protos.LocationData.Builder, tme.edgetrip.protos.LocationDataOrBuilder> 
        getLocationDataFieldBuilder() {
      if (locationDataBuilder_ == null) {
        locationDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            tme.edgetrip.protos.LocationData, tme.edgetrip.protos.LocationData.Builder, tme.edgetrip.protos.LocationDataOrBuilder>(
                locationData_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        locationData_ = null;
      }
      return locationDataBuilder_;
    }

    private java.util.List<tme.edgetrip.protos.CanData> canData_ =
      java.util.Collections.emptyList();
    private void ensureCanDataIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        canData_ = new java.util.ArrayList<tme.edgetrip.protos.CanData>(canData_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        tme.edgetrip.protos.CanData, tme.edgetrip.protos.CanData.Builder, tme.edgetrip.protos.CanDataOrBuilder> canDataBuilder_;

    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public java.util.List<tme.edgetrip.protos.CanData> getCanDataList() {
      if (canDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(canData_);
      } else {
        return canDataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public int getCanDataCount() {
      if (canDataBuilder_ == null) {
        return canData_.size();
      } else {
        return canDataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public tme.edgetrip.protos.CanData getCanData(int index) {
      if (canDataBuilder_ == null) {
        return canData_.get(index);
      } else {
        return canDataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder setCanData(
        int index, tme.edgetrip.protos.CanData value) {
      if (canDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCanDataIsMutable();
        canData_.set(index, value);
        onChanged();
      } else {
        canDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder setCanData(
        int index, tme.edgetrip.protos.CanData.Builder builderForValue) {
      if (canDataBuilder_ == null) {
        ensureCanDataIsMutable();
        canData_.set(index, builderForValue.build());
        onChanged();
      } else {
        canDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder addCanData(tme.edgetrip.protos.CanData value) {
      if (canDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCanDataIsMutable();
        canData_.add(value);
        onChanged();
      } else {
        canDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder addCanData(
        int index, tme.edgetrip.protos.CanData value) {
      if (canDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCanDataIsMutable();
        canData_.add(index, value);
        onChanged();
      } else {
        canDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder addCanData(
        tme.edgetrip.protos.CanData.Builder builderForValue) {
      if (canDataBuilder_ == null) {
        ensureCanDataIsMutable();
        canData_.add(builderForValue.build());
        onChanged();
      } else {
        canDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder addCanData(
        int index, tme.edgetrip.protos.CanData.Builder builderForValue) {
      if (canDataBuilder_ == null) {
        ensureCanDataIsMutable();
        canData_.add(index, builderForValue.build());
        onChanged();
      } else {
        canDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder addAllCanData(
        java.lang.Iterable<? extends tme.edgetrip.protos.CanData> values) {
      if (canDataBuilder_ == null) {
        ensureCanDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, canData_);
        onChanged();
      } else {
        canDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder clearCanData() {
      if (canDataBuilder_ == null) {
        canData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        canDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public Builder removeCanData(int index) {
      if (canDataBuilder_ == null) {
        ensureCanDataIsMutable();
        canData_.remove(index);
        onChanged();
      } else {
        canDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public tme.edgetrip.protos.CanData.Builder getCanDataBuilder(
        int index) {
      return getCanDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public tme.edgetrip.protos.CanDataOrBuilder getCanDataOrBuilder(
        int index) {
      if (canDataBuilder_ == null) {
        return canData_.get(index);  } else {
        return canDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public java.util.List<? extends tme.edgetrip.protos.CanDataOrBuilder> 
         getCanDataOrBuilderList() {
      if (canDataBuilder_ != null) {
        return canDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(canData_);
      }
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public tme.edgetrip.protos.CanData.Builder addCanDataBuilder() {
      return getCanDataFieldBuilder().addBuilder(
          tme.edgetrip.protos.CanData.getDefaultInstance());
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public tme.edgetrip.protos.CanData.Builder addCanDataBuilder(
        int index) {
      return getCanDataFieldBuilder().addBuilder(
          index, tme.edgetrip.protos.CanData.getDefaultInstance());
    }
    /**
     * <pre>
     * Periodic CAN Data Collection
     * </pre>
     *
     * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
     */
    public java.util.List<tme.edgetrip.protos.CanData.Builder> 
         getCanDataBuilderList() {
      return getCanDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        tme.edgetrip.protos.CanData, tme.edgetrip.protos.CanData.Builder, tme.edgetrip.protos.CanDataOrBuilder> 
        getCanDataFieldBuilder() {
      if (canDataBuilder_ == null) {
        canDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            tme.edgetrip.protos.CanData, tme.edgetrip.protos.CanData.Builder, tme.edgetrip.protos.CanDataOrBuilder>(
                canData_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        canData_ = null;
      }
      return canDataBuilder_;
    }

    private tme.edgetrip.protos.DrivingScore drivingScore_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.DrivingScore, tme.edgetrip.protos.DrivingScore.Builder, tme.edgetrip.protos.DrivingScoreOrBuilder> drivingScoreBuilder_;
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     * @return Whether the drivingScore field is set.
     */
    public boolean hasDrivingScore() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     * @return The drivingScore.
     */
    public tme.edgetrip.protos.DrivingScore getDrivingScore() {
      if (drivingScoreBuilder_ == null) {
        return drivingScore_ == null ? tme.edgetrip.protos.DrivingScore.getDefaultInstance() : drivingScore_;
      } else {
        return drivingScoreBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    public Builder setDrivingScore(tme.edgetrip.protos.DrivingScore value) {
      if (drivingScoreBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        drivingScore_ = value;
      } else {
        drivingScoreBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    public Builder setDrivingScore(
        tme.edgetrip.protos.DrivingScore.Builder builderForValue) {
      if (drivingScoreBuilder_ == null) {
        drivingScore_ = builderForValue.build();
      } else {
        drivingScoreBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    public Builder mergeDrivingScore(tme.edgetrip.protos.DrivingScore value) {
      if (drivingScoreBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          drivingScore_ != null &&
          drivingScore_ != tme.edgetrip.protos.DrivingScore.getDefaultInstance()) {
          getDrivingScoreBuilder().mergeFrom(value);
        } else {
          drivingScore_ = value;
        }
      } else {
        drivingScoreBuilder_.mergeFrom(value);
      }
      if (drivingScore_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    public Builder clearDrivingScore() {
      bitField0_ = (bitField0_ & ~0x00000020);
      drivingScore_ = null;
      if (drivingScoreBuilder_ != null) {
        drivingScoreBuilder_.dispose();
        drivingScoreBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    public tme.edgetrip.protos.DrivingScore.Builder getDrivingScoreBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getDrivingScoreFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    public tme.edgetrip.protos.DrivingScoreOrBuilder getDrivingScoreOrBuilder() {
      if (drivingScoreBuilder_ != null) {
        return drivingScoreBuilder_.getMessageOrBuilder();
      } else {
        return drivingScore_ == null ?
            tme.edgetrip.protos.DrivingScore.getDefaultInstance() : drivingScore_;
      }
    }
    /**
     * <pre>
     * Hybrid Score
     * </pre>
     *
     * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.DrivingScore, tme.edgetrip.protos.DrivingScore.Builder, tme.edgetrip.protos.DrivingScoreOrBuilder> 
        getDrivingScoreFieldBuilder() {
      if (drivingScoreBuilder_ == null) {
        drivingScoreBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tme.edgetrip.protos.DrivingScore, tme.edgetrip.protos.DrivingScore.Builder, tme.edgetrip.protos.DrivingScoreOrBuilder>(
                getDrivingScore(),
                getParentForChildren(),
                isClean());
        drivingScore_ = null;
      }
      return drivingScoreBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:edgetrip_v1.EdgeTripMessage)
  }

  // @@protoc_insertion_point(class_scope:edgetrip_v1.EdgeTripMessage)
  private static final tme.edgetrip.protos.EdgeTripMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tme.edgetrip.protos.EdgeTripMessage();
  }

  public static tme.edgetrip.protos.EdgeTripMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EdgeTripMessage>
      PARSER = new com.google.protobuf.AbstractParser<EdgeTripMessage>() {
    @java.lang.Override
    public EdgeTripMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EdgeTripMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EdgeTripMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tme.edgetrip.protos.EdgeTripMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

