// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

public interface EdgeTripMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:edgetrip_v1.EdgeTripMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * UNIX timestamp of the creation of the trip message (YYYY_MM_DD HH:MM:SS)
   * </pre>
   *
   * <code>int32 messageCreation = 1;</code>
   * @return The messageCreation.
   */
  int getMessageCreation();

  /**
   * <pre>
   * Version of the protobuf data schema (1)
   * </pre>
   *
   * <code>int32 dataVersion = 2;</code>
   * @return The dataVersion.
   */
  int getDataVersion();

  /**
   * <pre>
   * Trip Summary Data
   * </pre>
   *
   * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
   * @return Whether the tripSummary field is set.
   */
  boolean hasTripSummary();
  /**
   * <pre>
   * Trip Summary Data
   * </pre>
   *
   * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
   * @return The tripSummary.
   */
  tme.edgetrip.protos.TripSummary getTripSummary();
  /**
   * <pre>
   * Trip Summary Data
   * </pre>
   *
   * <code>.edgetrip_v1.TripSummary tripSummary = 3;</code>
   */
  tme.edgetrip.protos.TripSummaryOrBuilder getTripSummaryOrBuilder();

  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  java.util.List<tme.edgetrip.protos.LocationData> 
      getLocationDataList();
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  tme.edgetrip.protos.LocationData getLocationData(int index);
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  int getLocationDataCount();
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  java.util.List<? extends tme.edgetrip.protos.LocationDataOrBuilder> 
      getLocationDataOrBuilderList();
  /**
   * <pre>
   * Periodic Location Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.LocationData locationData = 4;</code>
   */
  tme.edgetrip.protos.LocationDataOrBuilder getLocationDataOrBuilder(
      int index);

  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  java.util.List<tme.edgetrip.protos.CanData> 
      getCanDataList();
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  tme.edgetrip.protos.CanData getCanData(int index);
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  int getCanDataCount();
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  java.util.List<? extends tme.edgetrip.protos.CanDataOrBuilder> 
      getCanDataOrBuilderList();
  /**
   * <pre>
   * Periodic CAN Data Collection
   * </pre>
   *
   * <code>repeated .edgetrip_v1.CanData canData = 5;</code>
   */
  tme.edgetrip.protos.CanDataOrBuilder getCanDataOrBuilder(
      int index);

  /**
   * <pre>
   * Hybrid Score
   * </pre>
   *
   * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
   * @return Whether the drivingScore field is set.
   */
  boolean hasDrivingScore();
  /**
   * <pre>
   * Hybrid Score
   * </pre>
   *
   * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
   * @return The drivingScore.
   */
  tme.edgetrip.protos.DrivingScore getDrivingScore();
  /**
   * <pre>
   * Hybrid Score
   * </pre>
   *
   * <code>.edgetrip_v1.DrivingScore drivingScore = 6;</code>
   */
  tme.edgetrip.protos.DrivingScoreOrBuilder getDrivingScoreOrBuilder();
}
