// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

/**
 * <pre>
 * Location data collection
 * </pre>
 *
 * Protobuf type {@code edgetrip_v1.LocationData}
 */
public final class LocationData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:edgetrip_v1.LocationData)
    LocationDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationData.newBuilder() to construct.
  private LocationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LocationData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_LocationData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_LocationData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tme.edgetrip.protos.LocationData.class, tme.edgetrip.protos.LocationData.Builder.class);
  }

  private int bitField0_;
  public static final int LOCATIONTIMESTAMP_FIELD_NUMBER = 1;
  private int locationTimestamp_ = 0;
  /**
   * <pre>
   * UNIX timestamp of the data point
   * </pre>
   *
   * <code>int32 locationTimestamp = 1;</code>
   * @return The locationTimestamp.
   */
  @java.lang.Override
  public int getLocationTimestamp() {
    return locationTimestamp_;
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private tme.edgetrip.protos.PositionInformation position_;
  /**
   * <pre>
   * Location information
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation position = 2;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Location information
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation position = 2;</code>
   * @return The position.
   */
  @java.lang.Override
  public tme.edgetrip.protos.PositionInformation getPosition() {
    return position_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : position_;
  }
  /**
   * <pre>
   * Location information
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation position = 2;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.PositionInformationOrBuilder getPositionOrBuilder() {
    return position_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : position_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (locationTimestamp_ != 0) {
      output.writeInt32(1, locationTimestamp_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPosition());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (locationTimestamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, locationTimestamp_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tme.edgetrip.protos.LocationData)) {
      return super.equals(obj);
    }
    tme.edgetrip.protos.LocationData other = (tme.edgetrip.protos.LocationData) obj;

    if (getLocationTimestamp()
        != other.getLocationTimestamp()) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCATIONTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getLocationTimestamp();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tme.edgetrip.protos.LocationData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tme.edgetrip.protos.LocationData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tme.edgetrip.protos.LocationData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.LocationData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tme.edgetrip.protos.LocationData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Location data collection
   * </pre>
   *
   * Protobuf type {@code edgetrip_v1.LocationData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:edgetrip_v1.LocationData)
      tme.edgetrip.protos.LocationDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_LocationData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_LocationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tme.edgetrip.protos.LocationData.class, tme.edgetrip.protos.LocationData.Builder.class);
    }

    // Construct using tme.edgetrip.protos.LocationData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      locationTimestamp_ = 0;
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_LocationData_descriptor;
    }

    @java.lang.Override
    public tme.edgetrip.protos.LocationData getDefaultInstanceForType() {
      return tme.edgetrip.protos.LocationData.getDefaultInstance();
    }

    @java.lang.Override
    public tme.edgetrip.protos.LocationData build() {
      tme.edgetrip.protos.LocationData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tme.edgetrip.protos.LocationData buildPartial() {
      tme.edgetrip.protos.LocationData result = new tme.edgetrip.protos.LocationData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tme.edgetrip.protos.LocationData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.locationTimestamp_ = locationTimestamp_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tme.edgetrip.protos.LocationData) {
        return mergeFrom((tme.edgetrip.protos.LocationData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tme.edgetrip.protos.LocationData other) {
      if (other == tme.edgetrip.protos.LocationData.getDefaultInstance()) return this;
      if (other.getLocationTimestamp() != 0) {
        setLocationTimestamp(other.getLocationTimestamp());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              locationTimestamp_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int locationTimestamp_ ;
    /**
     * <pre>
     * UNIX timestamp of the data point
     * </pre>
     *
     * <code>int32 locationTimestamp = 1;</code>
     * @return The locationTimestamp.
     */
    @java.lang.Override
    public int getLocationTimestamp() {
      return locationTimestamp_;
    }
    /**
     * <pre>
     * UNIX timestamp of the data point
     * </pre>
     *
     * <code>int32 locationTimestamp = 1;</code>
     * @param value The locationTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setLocationTimestamp(int value) {

      locationTimestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UNIX timestamp of the data point
     * </pre>
     *
     * <code>int32 locationTimestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocationTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      locationTimestamp_ = 0;
      onChanged();
      return this;
    }

    private tme.edgetrip.protos.PositionInformation position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder> positionBuilder_;
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     * @return The position.
     */
    public tme.edgetrip.protos.PositionInformation getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    public Builder setPosition(tme.edgetrip.protos.PositionInformation value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    public Builder setPosition(
        tme.edgetrip.protos.PositionInformation.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    public Builder mergePosition(tme.edgetrip.protos.PositionInformation value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          position_ != null &&
          position_ != tme.edgetrip.protos.PositionInformation.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    public tme.edgetrip.protos.PositionInformation.Builder getPositionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    public tme.edgetrip.protos.PositionInformationOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            tme.edgetrip.protos.PositionInformation.getDefaultInstance() : position_;
      }
    }
    /**
     * <pre>
     * Location information
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:edgetrip_v1.LocationData)
  }

  // @@protoc_insertion_point(class_scope:edgetrip_v1.LocationData)
  private static final tme.edgetrip.protos.LocationData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tme.edgetrip.protos.LocationData();
  }

  public static tme.edgetrip.protos.LocationData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationData>
      PARSER = new com.google.protobuf.AbstractParser<LocationData>() {
    @java.lang.Override
    public LocationData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LocationData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tme.edgetrip.protos.LocationData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

