// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

public interface LocationDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:edgetrip_v1.LocationData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * UNIX timestamp of the data point
   * </pre>
   *
   * <code>int32 locationTimestamp = 1;</code>
   * @return The locationTimestamp.
   */
  int getLocationTimestamp();

  /**
   * <pre>
   * Location information
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <pre>
   * Location information
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation position = 2;</code>
   * @return The position.
   */
  tme.edgetrip.protos.PositionInformation getPosition();
  /**
   * <pre>
   * Location information
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation position = 2;</code>
   */
  tme.edgetrip.protos.PositionInformationOrBuilder getPositionOrBuilder();
}
