// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

/**
 * <pre>
 * Trip summary data message
 * </pre>
 *
 * Protobuf type {@code edgetrip_v1.TripSummary}
 */
public final class TripSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:edgetrip_v1.TripSummary)
    TripSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TripSummary.newBuilder() to construct.
  private TripSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TripSummary() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TripSummary();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_TripSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_TripSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tme.edgetrip.protos.TripSummary.class, tme.edgetrip.protos.TripSummary.Builder.class);
  }

  private int bitField0_;
  public static final int TRIPSTARTTIME_FIELD_NUMBER = 1;
  private int tripStartTime_ = 0;
  /**
   * <pre>
   * UNIX timestamp of the start of the trip
   * </pre>
   *
   * <code>int32 tripStartTime = 1;</code>
   * @return The tripStartTime.
   */
  @java.lang.Override
  public int getTripStartTime() {
    return tripStartTime_;
  }

  public static final int TRIPSTARTLOCATION_FIELD_NUMBER = 2;
  private tme.edgetrip.protos.PositionInformation tripStartLocation_;
  /**
   * <pre>
   * Location at the start of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
   * @return Whether the tripStartLocation field is set.
   */
  @java.lang.Override
  public boolean hasTripStartLocation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Location at the start of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
   * @return The tripStartLocation.
   */
  @java.lang.Override
  public tme.edgetrip.protos.PositionInformation getTripStartLocation() {
    return tripStartLocation_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripStartLocation_;
  }
  /**
   * <pre>
   * Location at the start of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.PositionInformationOrBuilder getTripStartLocationOrBuilder() {
    return tripStartLocation_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripStartLocation_;
  }

  public static final int TRIPENDTIME_FIELD_NUMBER = 3;
  private int tripEndTime_ = 0;
  /**
   * <pre>
   * UNIX timestamp of the end of the trip
   * </pre>
   *
   * <code>int32 tripEndTime = 3;</code>
   * @return The tripEndTime.
   */
  @java.lang.Override
  public int getTripEndTime() {
    return tripEndTime_;
  }

  public static final int TRIPENDLOCATION_FIELD_NUMBER = 4;
  private tme.edgetrip.protos.PositionInformation tripEndLocation_;
  /**
   * <pre>
   * Location at the end of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
   * @return Whether the tripEndLocation field is set.
   */
  @java.lang.Override
  public boolean hasTripEndLocation() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Location at the end of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
   * @return The tripEndLocation.
   */
  @java.lang.Override
  public tme.edgetrip.protos.PositionInformation getTripEndLocation() {
    return tripEndLocation_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripEndLocation_;
  }
  /**
   * <pre>
   * Location at the end of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
   */
  @java.lang.Override
  public tme.edgetrip.protos.PositionInformationOrBuilder getTripEndLocationOrBuilder() {
    return tripEndLocation_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripEndLocation_;
  }

  public static final int TRIPLENGTH_FIELD_NUMBER = 5;
  private double tripLength_ = 0D;
  /**
   * <pre>
   * Total mileage of the trip, in meters
   * </pre>
   *
   * <code>double tripLength = 5;</code>
   * @return The tripLength.
   */
  @java.lang.Override
  public double getTripLength() {
    return tripLength_;
  }

  public static final int TRIPDURATION_FIELD_NUMBER = 6;
  private int tripDuration_ = 0;
  /**
   * <pre>
   * Trip duration, in seconds
   * </pre>
   *
   * <code>int32 tripDuration = 6;</code>
   * @return The tripDuration.
   */
  @java.lang.Override
  public int getTripDuration() {
    return tripDuration_;
  }

  public static final int TRIPDURATIONIDLE_FIELD_NUMBER = 7;
  private int tripDurationIdle_ = 0;
  /**
   * <pre>
   * Accumulated idle time during the trip, in seconds
   * </pre>
   *
   * <code>int32 tripDurationIdle = 7;</code>
   * @return The tripDurationIdle.
   */
  @java.lang.Override
  public int getTripDurationIdle() {
    return tripDurationIdle_;
  }

  public static final int TRIPDURATIONHIGHWAY_FIELD_NUMBER = 8;
  private int tripDurationHighway_ = 0;
  /**
   * <pre>
   * Accumulated highway time during the trip, in seconds
   * </pre>
   *
   * <code>int32 tripDurationHighway = 8;</code>
   * @return The tripDurationHighway.
   */
  @java.lang.Override
  public int getTripDurationHighway() {
    return tripDurationHighway_;
  }

  public static final int TRIPMAXSPEED_FIELD_NUMBER = 9;
  private double tripMaxSpeed_ = 0D;
  /**
   * <pre>
   * Maximum speed of the trip, in kph
   * </pre>
   *
   * <code>double tripMaxSpeed = 9;</code>
   * @return The tripMaxSpeed.
   */
  @java.lang.Override
  public double getTripMaxSpeed() {
    return tripMaxSpeed_;
  }

  public static final int TRIPAVGSPEED_FIELD_NUMBER = 10;
  private double tripAvgSpeed_ = 0D;
  /**
   * <pre>
   * Average speed of the trip, in kph
   * </pre>
   *
   * <code>double tripAvgSpeed = 10;</code>
   * @return The tripAvgSpeed.
   */
  @java.lang.Override
  public double getTripAvgSpeed() {
    return tripAvgSpeed_;
  }

  public static final int SOCSTARTTRIP_FIELD_NUMBER = 11;
  private int socStartTrip_ = 0;
  /**
   * <pre>
   * State of chare at start of trip, (%)
   * </pre>
   *
   * <code>int32 socStartTrip = 11;</code>
   * @return The socStartTrip.
   */
  @java.lang.Override
  public int getSocStartTrip() {
    return socStartTrip_;
  }

  public static final int SOCENDTRIP_FIELD_NUMBER = 12;
  private int socEndTrip_ = 0;
  /**
   * <pre>
   * State of chare at end of trip, (%)
   * </pre>
   *
   * <code>int32 socEndTrip = 12;</code>
   * @return The socEndTrip.
   */
  @java.lang.Override
  public int getSocEndTrip() {
    return socEndTrip_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tripStartTime_ != 0) {
      output.writeInt32(1, tripStartTime_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTripStartLocation());
    }
    if (tripEndTime_ != 0) {
      output.writeInt32(3, tripEndTime_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getTripEndLocation());
    }
    if (java.lang.Double.doubleToRawLongBits(tripLength_) != 0) {
      output.writeDouble(5, tripLength_);
    }
    if (tripDuration_ != 0) {
      output.writeInt32(6, tripDuration_);
    }
    if (tripDurationIdle_ != 0) {
      output.writeInt32(7, tripDurationIdle_);
    }
    if (tripDurationHighway_ != 0) {
      output.writeInt32(8, tripDurationHighway_);
    }
    if (java.lang.Double.doubleToRawLongBits(tripMaxSpeed_) != 0) {
      output.writeDouble(9, tripMaxSpeed_);
    }
    if (java.lang.Double.doubleToRawLongBits(tripAvgSpeed_) != 0) {
      output.writeDouble(10, tripAvgSpeed_);
    }
    if (socStartTrip_ != 0) {
      output.writeInt32(11, socStartTrip_);
    }
    if (socEndTrip_ != 0) {
      output.writeInt32(12, socEndTrip_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tripStartTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, tripStartTime_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTripStartLocation());
    }
    if (tripEndTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tripEndTime_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTripEndLocation());
    }
    if (java.lang.Double.doubleToRawLongBits(tripLength_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, tripLength_);
    }
    if (tripDuration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, tripDuration_);
    }
    if (tripDurationIdle_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, tripDurationIdle_);
    }
    if (tripDurationHighway_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, tripDurationHighway_);
    }
    if (java.lang.Double.doubleToRawLongBits(tripMaxSpeed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, tripMaxSpeed_);
    }
    if (java.lang.Double.doubleToRawLongBits(tripAvgSpeed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, tripAvgSpeed_);
    }
    if (socStartTrip_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, socStartTrip_);
    }
    if (socEndTrip_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, socEndTrip_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tme.edgetrip.protos.TripSummary)) {
      return super.equals(obj);
    }
    tme.edgetrip.protos.TripSummary other = (tme.edgetrip.protos.TripSummary) obj;

    if (getTripStartTime()
        != other.getTripStartTime()) return false;
    if (hasTripStartLocation() != other.hasTripStartLocation()) return false;
    if (hasTripStartLocation()) {
      if (!getTripStartLocation()
          .equals(other.getTripStartLocation())) return false;
    }
    if (getTripEndTime()
        != other.getTripEndTime()) return false;
    if (hasTripEndLocation() != other.hasTripEndLocation()) return false;
    if (hasTripEndLocation()) {
      if (!getTripEndLocation()
          .equals(other.getTripEndLocation())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getTripLength())
        != java.lang.Double.doubleToLongBits(
            other.getTripLength())) return false;
    if (getTripDuration()
        != other.getTripDuration()) return false;
    if (getTripDurationIdle()
        != other.getTripDurationIdle()) return false;
    if (getTripDurationHighway()
        != other.getTripDurationHighway()) return false;
    if (java.lang.Double.doubleToLongBits(getTripMaxSpeed())
        != java.lang.Double.doubleToLongBits(
            other.getTripMaxSpeed())) return false;
    if (java.lang.Double.doubleToLongBits(getTripAvgSpeed())
        != java.lang.Double.doubleToLongBits(
            other.getTripAvgSpeed())) return false;
    if (getSocStartTrip()
        != other.getSocStartTrip()) return false;
    if (getSocEndTrip()
        != other.getSocEndTrip()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRIPSTARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getTripStartTime();
    if (hasTripStartLocation()) {
      hash = (37 * hash) + TRIPSTARTLOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getTripStartLocation().hashCode();
    }
    hash = (37 * hash) + TRIPENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getTripEndTime();
    if (hasTripEndLocation()) {
      hash = (37 * hash) + TRIPENDLOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getTripEndLocation().hashCode();
    }
    hash = (37 * hash) + TRIPLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTripLength()));
    hash = (37 * hash) + TRIPDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getTripDuration();
    hash = (37 * hash) + TRIPDURATIONIDLE_FIELD_NUMBER;
    hash = (53 * hash) + getTripDurationIdle();
    hash = (37 * hash) + TRIPDURATIONHIGHWAY_FIELD_NUMBER;
    hash = (53 * hash) + getTripDurationHighway();
    hash = (37 * hash) + TRIPMAXSPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTripMaxSpeed()));
    hash = (37 * hash) + TRIPAVGSPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTripAvgSpeed()));
    hash = (37 * hash) + SOCSTARTTRIP_FIELD_NUMBER;
    hash = (53 * hash) + getSocStartTrip();
    hash = (37 * hash) + SOCENDTRIP_FIELD_NUMBER;
    hash = (53 * hash) + getSocEndTrip();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tme.edgetrip.protos.TripSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tme.edgetrip.protos.TripSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tme.edgetrip.protos.TripSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tme.edgetrip.protos.TripSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tme.edgetrip.protos.TripSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Trip summary data message
   * </pre>
   *
   * Protobuf type {@code edgetrip_v1.TripSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:edgetrip_v1.TripSummary)
      tme.edgetrip.protos.TripSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_TripSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_TripSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tme.edgetrip.protos.TripSummary.class, tme.edgetrip.protos.TripSummary.Builder.class);
    }

    // Construct using tme.edgetrip.protos.TripSummary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTripStartLocationFieldBuilder();
        getTripEndLocationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tripStartTime_ = 0;
      tripStartLocation_ = null;
      if (tripStartLocationBuilder_ != null) {
        tripStartLocationBuilder_.dispose();
        tripStartLocationBuilder_ = null;
      }
      tripEndTime_ = 0;
      tripEndLocation_ = null;
      if (tripEndLocationBuilder_ != null) {
        tripEndLocationBuilder_.dispose();
        tripEndLocationBuilder_ = null;
      }
      tripLength_ = 0D;
      tripDuration_ = 0;
      tripDurationIdle_ = 0;
      tripDurationHighway_ = 0;
      tripMaxSpeed_ = 0D;
      tripAvgSpeed_ = 0D;
      socStartTrip_ = 0;
      socEndTrip_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tme.edgetrip.protos.EdgeTripProtos.internal_static_edgetrip_v1_TripSummary_descriptor;
    }

    @java.lang.Override
    public tme.edgetrip.protos.TripSummary getDefaultInstanceForType() {
      return tme.edgetrip.protos.TripSummary.getDefaultInstance();
    }

    @java.lang.Override
    public tme.edgetrip.protos.TripSummary build() {
      tme.edgetrip.protos.TripSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tme.edgetrip.protos.TripSummary buildPartial() {
      tme.edgetrip.protos.TripSummary result = new tme.edgetrip.protos.TripSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tme.edgetrip.protos.TripSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tripStartTime_ = tripStartTime_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tripStartLocation_ = tripStartLocationBuilder_ == null
            ? tripStartLocation_
            : tripStartLocationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tripEndTime_ = tripEndTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tripEndLocation_ = tripEndLocationBuilder_ == null
            ? tripEndLocation_
            : tripEndLocationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tripLength_ = tripLength_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tripDuration_ = tripDuration_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.tripDurationIdle_ = tripDurationIdle_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.tripDurationHighway_ = tripDurationHighway_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.tripMaxSpeed_ = tripMaxSpeed_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.tripAvgSpeed_ = tripAvgSpeed_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.socStartTrip_ = socStartTrip_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.socEndTrip_ = socEndTrip_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tme.edgetrip.protos.TripSummary) {
        return mergeFrom((tme.edgetrip.protos.TripSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tme.edgetrip.protos.TripSummary other) {
      if (other == tme.edgetrip.protos.TripSummary.getDefaultInstance()) return this;
      if (other.getTripStartTime() != 0) {
        setTripStartTime(other.getTripStartTime());
      }
      if (other.hasTripStartLocation()) {
        mergeTripStartLocation(other.getTripStartLocation());
      }
      if (other.getTripEndTime() != 0) {
        setTripEndTime(other.getTripEndTime());
      }
      if (other.hasTripEndLocation()) {
        mergeTripEndLocation(other.getTripEndLocation());
      }
      if (other.getTripLength() != 0D) {
        setTripLength(other.getTripLength());
      }
      if (other.getTripDuration() != 0) {
        setTripDuration(other.getTripDuration());
      }
      if (other.getTripDurationIdle() != 0) {
        setTripDurationIdle(other.getTripDurationIdle());
      }
      if (other.getTripDurationHighway() != 0) {
        setTripDurationHighway(other.getTripDurationHighway());
      }
      if (other.getTripMaxSpeed() != 0D) {
        setTripMaxSpeed(other.getTripMaxSpeed());
      }
      if (other.getTripAvgSpeed() != 0D) {
        setTripAvgSpeed(other.getTripAvgSpeed());
      }
      if (other.getSocStartTrip() != 0) {
        setSocStartTrip(other.getSocStartTrip());
      }
      if (other.getSocEndTrip() != 0) {
        setSocEndTrip(other.getSocEndTrip());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              tripStartTime_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getTripStartLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tripEndTime_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getTripEndLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 41: {
              tripLength_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              tripDuration_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              tripDurationIdle_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              tripDurationHighway_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 73: {
              tripMaxSpeed_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            case 81: {
              tripAvgSpeed_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 88: {
              socStartTrip_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              socEndTrip_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int tripStartTime_ ;
    /**
     * <pre>
     * UNIX timestamp of the start of the trip
     * </pre>
     *
     * <code>int32 tripStartTime = 1;</code>
     * @return The tripStartTime.
     */
    @java.lang.Override
    public int getTripStartTime() {
      return tripStartTime_;
    }
    /**
     * <pre>
     * UNIX timestamp of the start of the trip
     * </pre>
     *
     * <code>int32 tripStartTime = 1;</code>
     * @param value The tripStartTime to set.
     * @return This builder for chaining.
     */
    public Builder setTripStartTime(int value) {

      tripStartTime_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UNIX timestamp of the start of the trip
     * </pre>
     *
     * <code>int32 tripStartTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripStartTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tripStartTime_ = 0;
      onChanged();
      return this;
    }

    private tme.edgetrip.protos.PositionInformation tripStartLocation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder> tripStartLocationBuilder_;
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     * @return Whether the tripStartLocation field is set.
     */
    public boolean hasTripStartLocation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     * @return The tripStartLocation.
     */
    public tme.edgetrip.protos.PositionInformation getTripStartLocation() {
      if (tripStartLocationBuilder_ == null) {
        return tripStartLocation_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripStartLocation_;
      } else {
        return tripStartLocationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    public Builder setTripStartLocation(tme.edgetrip.protos.PositionInformation value) {
      if (tripStartLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tripStartLocation_ = value;
      } else {
        tripStartLocationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    public Builder setTripStartLocation(
        tme.edgetrip.protos.PositionInformation.Builder builderForValue) {
      if (tripStartLocationBuilder_ == null) {
        tripStartLocation_ = builderForValue.build();
      } else {
        tripStartLocationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    public Builder mergeTripStartLocation(tme.edgetrip.protos.PositionInformation value) {
      if (tripStartLocationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          tripStartLocation_ != null &&
          tripStartLocation_ != tme.edgetrip.protos.PositionInformation.getDefaultInstance()) {
          getTripStartLocationBuilder().mergeFrom(value);
        } else {
          tripStartLocation_ = value;
        }
      } else {
        tripStartLocationBuilder_.mergeFrom(value);
      }
      if (tripStartLocation_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    public Builder clearTripStartLocation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tripStartLocation_ = null;
      if (tripStartLocationBuilder_ != null) {
        tripStartLocationBuilder_.dispose();
        tripStartLocationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    public tme.edgetrip.protos.PositionInformation.Builder getTripStartLocationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTripStartLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    public tme.edgetrip.protos.PositionInformationOrBuilder getTripStartLocationOrBuilder() {
      if (tripStartLocationBuilder_ != null) {
        return tripStartLocationBuilder_.getMessageOrBuilder();
      } else {
        return tripStartLocation_ == null ?
            tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripStartLocation_;
      }
    }
    /**
     * <pre>
     * Location at the start of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder> 
        getTripStartLocationFieldBuilder() {
      if (tripStartLocationBuilder_ == null) {
        tripStartLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder>(
                getTripStartLocation(),
                getParentForChildren(),
                isClean());
        tripStartLocation_ = null;
      }
      return tripStartLocationBuilder_;
    }

    private int tripEndTime_ ;
    /**
     * <pre>
     * UNIX timestamp of the end of the trip
     * </pre>
     *
     * <code>int32 tripEndTime = 3;</code>
     * @return The tripEndTime.
     */
    @java.lang.Override
    public int getTripEndTime() {
      return tripEndTime_;
    }
    /**
     * <pre>
     * UNIX timestamp of the end of the trip
     * </pre>
     *
     * <code>int32 tripEndTime = 3;</code>
     * @param value The tripEndTime to set.
     * @return This builder for chaining.
     */
    public Builder setTripEndTime(int value) {

      tripEndTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UNIX timestamp of the end of the trip
     * </pre>
     *
     * <code>int32 tripEndTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripEndTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tripEndTime_ = 0;
      onChanged();
      return this;
    }

    private tme.edgetrip.protos.PositionInformation tripEndLocation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder> tripEndLocationBuilder_;
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     * @return Whether the tripEndLocation field is set.
     */
    public boolean hasTripEndLocation() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     * @return The tripEndLocation.
     */
    public tme.edgetrip.protos.PositionInformation getTripEndLocation() {
      if (tripEndLocationBuilder_ == null) {
        return tripEndLocation_ == null ? tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripEndLocation_;
      } else {
        return tripEndLocationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    public Builder setTripEndLocation(tme.edgetrip.protos.PositionInformation value) {
      if (tripEndLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tripEndLocation_ = value;
      } else {
        tripEndLocationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    public Builder setTripEndLocation(
        tme.edgetrip.protos.PositionInformation.Builder builderForValue) {
      if (tripEndLocationBuilder_ == null) {
        tripEndLocation_ = builderForValue.build();
      } else {
        tripEndLocationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    public Builder mergeTripEndLocation(tme.edgetrip.protos.PositionInformation value) {
      if (tripEndLocationBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          tripEndLocation_ != null &&
          tripEndLocation_ != tme.edgetrip.protos.PositionInformation.getDefaultInstance()) {
          getTripEndLocationBuilder().mergeFrom(value);
        } else {
          tripEndLocation_ = value;
        }
      } else {
        tripEndLocationBuilder_.mergeFrom(value);
      }
      if (tripEndLocation_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    public Builder clearTripEndLocation() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tripEndLocation_ = null;
      if (tripEndLocationBuilder_ != null) {
        tripEndLocationBuilder_.dispose();
        tripEndLocationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    public tme.edgetrip.protos.PositionInformation.Builder getTripEndLocationBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTripEndLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    public tme.edgetrip.protos.PositionInformationOrBuilder getTripEndLocationOrBuilder() {
      if (tripEndLocationBuilder_ != null) {
        return tripEndLocationBuilder_.getMessageOrBuilder();
      } else {
        return tripEndLocation_ == null ?
            tme.edgetrip.protos.PositionInformation.getDefaultInstance() : tripEndLocation_;
      }
    }
    /**
     * <pre>
     * Location at the end of the trip
     * </pre>
     *
     * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder> 
        getTripEndLocationFieldBuilder() {
      if (tripEndLocationBuilder_ == null) {
        tripEndLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tme.edgetrip.protos.PositionInformation, tme.edgetrip.protos.PositionInformation.Builder, tme.edgetrip.protos.PositionInformationOrBuilder>(
                getTripEndLocation(),
                getParentForChildren(),
                isClean());
        tripEndLocation_ = null;
      }
      return tripEndLocationBuilder_;
    }

    private double tripLength_ ;
    /**
     * <pre>
     * Total mileage of the trip, in meters
     * </pre>
     *
     * <code>double tripLength = 5;</code>
     * @return The tripLength.
     */
    @java.lang.Override
    public double getTripLength() {
      return tripLength_;
    }
    /**
     * <pre>
     * Total mileage of the trip, in meters
     * </pre>
     *
     * <code>double tripLength = 5;</code>
     * @param value The tripLength to set.
     * @return This builder for chaining.
     */
    public Builder setTripLength(double value) {

      tripLength_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total mileage of the trip, in meters
     * </pre>
     *
     * <code>double tripLength = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripLength() {
      bitField0_ = (bitField0_ & ~0x00000010);
      tripLength_ = 0D;
      onChanged();
      return this;
    }

    private int tripDuration_ ;
    /**
     * <pre>
     * Trip duration, in seconds
     * </pre>
     *
     * <code>int32 tripDuration = 6;</code>
     * @return The tripDuration.
     */
    @java.lang.Override
    public int getTripDuration() {
      return tripDuration_;
    }
    /**
     * <pre>
     * Trip duration, in seconds
     * </pre>
     *
     * <code>int32 tripDuration = 6;</code>
     * @param value The tripDuration to set.
     * @return This builder for chaining.
     */
    public Builder setTripDuration(int value) {

      tripDuration_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trip duration, in seconds
     * </pre>
     *
     * <code>int32 tripDuration = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripDuration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      tripDuration_ = 0;
      onChanged();
      return this;
    }

    private int tripDurationIdle_ ;
    /**
     * <pre>
     * Accumulated idle time during the trip, in seconds
     * </pre>
     *
     * <code>int32 tripDurationIdle = 7;</code>
     * @return The tripDurationIdle.
     */
    @java.lang.Override
    public int getTripDurationIdle() {
      return tripDurationIdle_;
    }
    /**
     * <pre>
     * Accumulated idle time during the trip, in seconds
     * </pre>
     *
     * <code>int32 tripDurationIdle = 7;</code>
     * @param value The tripDurationIdle to set.
     * @return This builder for chaining.
     */
    public Builder setTripDurationIdle(int value) {

      tripDurationIdle_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Accumulated idle time during the trip, in seconds
     * </pre>
     *
     * <code>int32 tripDurationIdle = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripDurationIdle() {
      bitField0_ = (bitField0_ & ~0x00000040);
      tripDurationIdle_ = 0;
      onChanged();
      return this;
    }

    private int tripDurationHighway_ ;
    /**
     * <pre>
     * Accumulated highway time during the trip, in seconds
     * </pre>
     *
     * <code>int32 tripDurationHighway = 8;</code>
     * @return The tripDurationHighway.
     */
    @java.lang.Override
    public int getTripDurationHighway() {
      return tripDurationHighway_;
    }
    /**
     * <pre>
     * Accumulated highway time during the trip, in seconds
     * </pre>
     *
     * <code>int32 tripDurationHighway = 8;</code>
     * @param value The tripDurationHighway to set.
     * @return This builder for chaining.
     */
    public Builder setTripDurationHighway(int value) {

      tripDurationHighway_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Accumulated highway time during the trip, in seconds
     * </pre>
     *
     * <code>int32 tripDurationHighway = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripDurationHighway() {
      bitField0_ = (bitField0_ & ~0x00000080);
      tripDurationHighway_ = 0;
      onChanged();
      return this;
    }

    private double tripMaxSpeed_ ;
    /**
     * <pre>
     * Maximum speed of the trip, in kph
     * </pre>
     *
     * <code>double tripMaxSpeed = 9;</code>
     * @return The tripMaxSpeed.
     */
    @java.lang.Override
    public double getTripMaxSpeed() {
      return tripMaxSpeed_;
    }
    /**
     * <pre>
     * Maximum speed of the trip, in kph
     * </pre>
     *
     * <code>double tripMaxSpeed = 9;</code>
     * @param value The tripMaxSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setTripMaxSpeed(double value) {

      tripMaxSpeed_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum speed of the trip, in kph
     * </pre>
     *
     * <code>double tripMaxSpeed = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripMaxSpeed() {
      bitField0_ = (bitField0_ & ~0x00000100);
      tripMaxSpeed_ = 0D;
      onChanged();
      return this;
    }

    private double tripAvgSpeed_ ;
    /**
     * <pre>
     * Average speed of the trip, in kph
     * </pre>
     *
     * <code>double tripAvgSpeed = 10;</code>
     * @return The tripAvgSpeed.
     */
    @java.lang.Override
    public double getTripAvgSpeed() {
      return tripAvgSpeed_;
    }
    /**
     * <pre>
     * Average speed of the trip, in kph
     * </pre>
     *
     * <code>double tripAvgSpeed = 10;</code>
     * @param value The tripAvgSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setTripAvgSpeed(double value) {

      tripAvgSpeed_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Average speed of the trip, in kph
     * </pre>
     *
     * <code>double tripAvgSpeed = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTripAvgSpeed() {
      bitField0_ = (bitField0_ & ~0x00000200);
      tripAvgSpeed_ = 0D;
      onChanged();
      return this;
    }

    private int socStartTrip_ ;
    /**
     * <pre>
     * State of chare at start of trip, (%)
     * </pre>
     *
     * <code>int32 socStartTrip = 11;</code>
     * @return The socStartTrip.
     */
    @java.lang.Override
    public int getSocStartTrip() {
      return socStartTrip_;
    }
    /**
     * <pre>
     * State of chare at start of trip, (%)
     * </pre>
     *
     * <code>int32 socStartTrip = 11;</code>
     * @param value The socStartTrip to set.
     * @return This builder for chaining.
     */
    public Builder setSocStartTrip(int value) {

      socStartTrip_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * State of chare at start of trip, (%)
     * </pre>
     *
     * <code>int32 socStartTrip = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocStartTrip() {
      bitField0_ = (bitField0_ & ~0x00000400);
      socStartTrip_ = 0;
      onChanged();
      return this;
    }

    private int socEndTrip_ ;
    /**
     * <pre>
     * State of chare at end of trip, (%)
     * </pre>
     *
     * <code>int32 socEndTrip = 12;</code>
     * @return The socEndTrip.
     */
    @java.lang.Override
    public int getSocEndTrip() {
      return socEndTrip_;
    }
    /**
     * <pre>
     * State of chare at end of trip, (%)
     * </pre>
     *
     * <code>int32 socEndTrip = 12;</code>
     * @param value The socEndTrip to set.
     * @return This builder for chaining.
     */
    public Builder setSocEndTrip(int value) {

      socEndTrip_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * State of chare at end of trip, (%)
     * </pre>
     *
     * <code>int32 socEndTrip = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocEndTrip() {
      bitField0_ = (bitField0_ & ~0x00000800);
      socEndTrip_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:edgetrip_v1.TripSummary)
  }

  // @@protoc_insertion_point(class_scope:edgetrip_v1.TripSummary)
  private static final tme.edgetrip.protos.TripSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tme.edgetrip.protos.TripSummary();
  }

  public static tme.edgetrip.protos.TripSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TripSummary>
      PARSER = new com.google.protobuf.AbstractParser<TripSummary>() {
    @java.lang.Override
    public TripSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TripSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TripSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tme.edgetrip.protos.TripSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

