// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgetrip_v1.proto

// Protobuf Java Version: 3.25.0
package tme.edgetrip.protos;

public interface TripSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:edgetrip_v1.TripSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * UNIX timestamp of the start of the trip
   * </pre>
   *
   * <code>int32 tripStartTime = 1;</code>
   * @return The tripStartTime.
   */
  int getTripStartTime();

  /**
   * <pre>
   * Location at the start of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
   * @return Whether the tripStartLocation field is set.
   */
  boolean hasTripStartLocation();
  /**
   * <pre>
   * Location at the start of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
   * @return The tripStartLocation.
   */
  tme.edgetrip.protos.PositionInformation getTripStartLocation();
  /**
   * <pre>
   * Location at the start of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripStartLocation = 2;</code>
   */
  tme.edgetrip.protos.PositionInformationOrBuilder getTripStartLocationOrBuilder();

  /**
   * <pre>
   * UNIX timestamp of the end of the trip
   * </pre>
   *
   * <code>int32 tripEndTime = 3;</code>
   * @return The tripEndTime.
   */
  int getTripEndTime();

  /**
   * <pre>
   * Location at the end of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
   * @return Whether the tripEndLocation field is set.
   */
  boolean hasTripEndLocation();
  /**
   * <pre>
   * Location at the end of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
   * @return The tripEndLocation.
   */
  tme.edgetrip.protos.PositionInformation getTripEndLocation();
  /**
   * <pre>
   * Location at the end of the trip
   * </pre>
   *
   * <code>.edgetrip_v1.PositionInformation tripEndLocation = 4;</code>
   */
  tme.edgetrip.protos.PositionInformationOrBuilder getTripEndLocationOrBuilder();

  /**
   * <pre>
   * Total mileage of the trip, in meters
   * </pre>
   *
   * <code>double tripLength = 5;</code>
   * @return The tripLength.
   */
  double getTripLength();

  /**
   * <pre>
   * Trip duration, in seconds
   * </pre>
   *
   * <code>int32 tripDuration = 6;</code>
   * @return The tripDuration.
   */
  int getTripDuration();

  /**
   * <pre>
   * Accumulated idle time during the trip, in seconds
   * </pre>
   *
   * <code>int32 tripDurationIdle = 7;</code>
   * @return The tripDurationIdle.
   */
  int getTripDurationIdle();

  /**
   * <pre>
   * Accumulated highway time during the trip, in seconds
   * </pre>
   *
   * <code>int32 tripDurationHighway = 8;</code>
   * @return The tripDurationHighway.
   */
  int getTripDurationHighway();

  /**
   * <pre>
   * Maximum speed of the trip, in kph
   * </pre>
   *
   * <code>double tripMaxSpeed = 9;</code>
   * @return The tripMaxSpeed.
   */
  double getTripMaxSpeed();

  /**
   * <pre>
   * Average speed of the trip, in kph
   * </pre>
   *
   * <code>double tripAvgSpeed = 10;</code>
   * @return The tripAvgSpeed.
   */
  double getTripAvgSpeed();

  /**
   * <pre>
   * State of chare at start of trip, (%)
   * </pre>
   *
   * <code>int32 socStartTrip = 11;</code>
   * @return The socStartTrip.
   */
  int getSocStartTrip();

  /**
   * <pre>
   * State of chare at end of trip, (%)
   * </pre>
   *
   * <code>int32 socEndTrip = 12;</code>
   * @return The socEndTrip.
   */
  int getSocEndTrip();
}
